- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled

- name: restart elasticsearch
  become: yes
  service: name=elasticsearch state=restarted enabled=yes

- name: stop elasticsearch
  become: yes
  service: name=elasticsearch state=stopped enabled=yes