--- 
#install java
- name: Add openjdk-8-jdk repository
  apt_repository:
   repo: ppa:openjdk-r/ppa

- name: Refresh java repo
  become: yes
  apt: update_cache=yes
  
  
- name: Install openjdk-8-jdk
  apt:
    name: openjdk-8-jdk
    state: present

- name: register open_jdk version
  shell: java -version 2>&1 | grep OpenJDK
  register: open_jdk
  ignore_errors: yes

- name: refresh the java ca-certificates
  become: yes
  command: /var/lib/dpkg/info/ca-certificates-java.postinst configure
  when: ansible_distribution == 'Ubuntu' and open_jdk.rc == 0
  

#- name: download deb package
#  get_url:
#    dest: "/etc/{{ elasticsearch_deb_file }}"
#    url: "https://artifacts.elastic.co/downloads/elasticsearch/{{ elasticsearch_deb_file }}"
#    checksum: "sha512:https://artifacts.elastic.co/downloads/elasticsearch/{{ elasticsearch_deb_file }}.sha512"
#  become: yes

#- name: install from deb package
#  apt:
#    deb: "/etc/{{ elasticsearch_deb_file }}"
#  become: yes